- name: Create a group for "webapps"
  group:
    name: webapps
    state: present

- name: Add the user 'webapps' with a bash shell, appending the group 'webapps' to the user's groups
  user:
    name: webapps
    shell: /bin/bash
    home: /usr/src/webapps
    groups: webapps
    append: yes
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
