---
- name: Ensure Certbot PPA is installed.
  apt_repository:
    repo: ppa:certbot/certbot

- name: Ensure python-certbot-nginx is installed.
  package:
    name: python-certbot-nginx
    state: present

- name: Ensure ssl-cert is installed.
  package:
    name: ssl-cert
    state: present

- name: Ensure SSL default snakeoil certificate is installed.
  command: "make-ssl-cert generate-default-snakeoil --force-overwrite"

- name: Ensure SSL certificate is installed.
  command: "certbot --nginx --non-interactive --agree-tos -m nficano@gmail.com -d nickficano.com -d www.nickficano.com -d api.nickficano.com --expand"

- name: install openssl
  package:
    name: openssl
    state: latest

- name: create output directory for dhparam
  file:
    path: /etc/ssl
    state: directory

- name: generate diffie-hellman parameter file
  command: "openssl dhparam -dsaparam -out '/etc/ssl/dhparam-4096.pem' 4096"
  args:
    creates: /etc/ssl/dhparam-4096.pem

- name: write cron for auto-regenerating dhparams
  cron:
    name: "Diffie-Hellman parameter update"
    job: openssl dhparam -dsaparam -out '/etc/ssl/dhparam-4096.pem' 4096
    state: present
    special_time: weekly

- name: write ssl dhparams configuration snippet for nginx
  template:
    src: templates/ssl-params.conf
    dest: /etc/nginx/snippets/ssl-params.conf
  notify:
    - reload nginx
  tags:
    - jump

- name: write ssl configuration snippet for nginx
  template:
    src: templates/ssl-snippets.conf
    dest: /etc/nginx/snippets/ssl-snippets.conf
  notify:
    - reload nginx
