---
- name: Ensure Certbot PPA is installed.
  apt_repository:
    repo: ppa:certbot/certbot

- name: Ensure python-certbot-nginx is installed.
  package:
    name: python-certbot-nginx
    state: present


- name: Ensure openssl is installed.
  package:
    name: openssl
    state: latest

- name: Ensure ssl-cert is installed.
  package:
    name: ssl-cert
    state: present

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/nickficano.com/cert.pem
  register: letsencrypt_cert

- import_tasks: create-cert.yml
  when: not letsencrypt_cert.stat.exists

- name: write cron for auto-regenerating dhparams
  cron:
    name: "Diffie-Hellman parameter update"
    job: openssl dhparam -dsaparam -out '/etc/ssl/dhparam-4096.pem' 4096
    state: present
    special_time: weekly

- name: write cron for certbot renewal
  cron:
    name: Certbot automatic renewal.
    job: "certbot renew --quiet --no-self-upgrade"
    minute: "30"
    hour: "3"
    user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

- name: write ssl dhparams configuration snippet for nginx
  template:
    src: templates/ssl-params.conf
    dest: /etc/nginx/snippets/ssl-params.conf
  notify:
    - reload nginx

- name: write ssl configuration snippet for nginx
  template:
    src: templates/ssl-snippets.conf
    dest: /etc/nginx/snippets/ssl-snippets.conf
  notify:
    - reload nginx
