version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ansible
    versions:
    - 2.10.0
    - 2.9.5
  - dependency-name: ipython
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
