---
# file: roles/common/tasks/main.yml

- name: Add public keys from Github.
  authorized_key:
    user: "{{ deploy_user }}"
    key: https://github.com/{{ item }}.keys
  with_items:
    - "nficano"

- name: Ensure aptitude is installed.
  package:
    name: aptitude
    state: present

- name: Ensure git-core is installed.
  package:
    name: git-core
    state: present
