---
- name: Ensure NGINX is installed.
  package:
    name: nginx
    state: present

- name: Write NGINX configuration
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: yes
  notify:
    - reload nginx
  tags:
    - jump

- name: Write NGINX vhosts
  template:
    src: templates/vhosts.conf
    dest: /etc/nginx/conf.d/com.nickficano.nginx.conf
  become: yes
  notify:
    - reload nginx

- name: Ensure snippets directory exists
  file:
    path: /etc/nginx/snippets
    state: directory
    follow: yes
  become: yes
