---

- hosts: webservers
  become: yes

  roles:
    # - carefuldog
    # - common
    # - ntp
    # - nginx
    # - users
    # - letsencrypt
    - nickficano.com
    - geerlingguy.nodejs
    - geerlingguy.pip
    - geerlingguy.supervisor
